# -*- coding: utf-8 -*-
"""internship

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZm-gV-9f5izPMbQrWPx6QHoK2kymZLj
"""
# the First way
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

model_name = "google/flan-t5-large"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    device_map="auto"
)

while True:
    question = input("Enter your question: ")

    clean_data = question.lower().strip()
    prompt= f"""
You are a chatbot.

Rules:
- If user says "hello" answer "Hi there"
- If user says "how are u" answer "I'm fine"
- If user says "bye" answer "good_bye"
- If user says "name" answer "I'm chatbot"
- If user says "help" answer "I can answer basic questions"
- If user says "are u here" answer "yes sir how can I help you"

User question: {clean_data}

Answer:
"""
    if clean_data == "exist":
        print("Thanks for using our chatbot")
        break

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=200
    )

    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)

    print("Answer:", answer)
